### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by chalermchai-phoc** [Arleng2017/github-crash-coruse#1]
I think is looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1{
   color:#efa82e;
}
```
